langiage: java

jdk:
  - openjdk6

sudo: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install curl jq screen openssl
  - sudo chmod -R 0775 /var/run/screen
  - mkdir .gossiperl-daemon
  - cd .gossiperl-daemon
  - git clone --depth=50 --branch=master https://github.com/gossiperl/gossiperl.git .
  - cd test
  - chmod +x install-erlang-with-kerl.sh
  - ./install-erlang-with-kerl.sh
  - cd ../..
  - chmod +x .gossiperl-daemon/test/run-for-unit-tests.sh
  - ./.gossiperl-daemon/test/run-for-unit-tests.sh

notifications:
  email: false